config/routes.rb
class SubdomainConstraint
  def self.matches?(request)
    subdomains = %w{www admin}
    request.subdomain.present? && !subdomains.include?(request.subdomain) && !request.subdomain.start_with?('www.')

  end
end

Rails.application.routes.draw do
  devise_for :users
  resources :tenants
   root 'tenants#index'



  constraints SubdomainConstraint do
    #put resources inside here if they are only available for subdomains
    resources :leases
  end
end

app/models/lease.rb
class Lease < ActiveRecord::Base
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base



  after_create :create_tenant

  #??do we need to drop the schema when destroy the tenants


  private

  def create_tenant
    Apartment::Tenant.create(subdomain)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  before_action :set_lease, only: [:show, :edit, :update, :destroy]

  # GET /leases
  # GET /leases.json
  def index
    @leases = Lease.all
  end

  # GET /leases/1
  # GET /leases/1.json
  def show
  end

  # GET /leases/new
  def new
    @lease = Lease.new
  end

  # GET /leases/1/edit
  def edit
  end

  # POST /leases
  # POST /leases.json
  def create
    @lease = Lease.new(lease_params)

    respond_to do |format|
      if @lease.save
        format.html { redirect_to @lease, notice: 'Lease was successfully created.' }
        format.json { render :show, status: :created, location: @lease }
      else
        format.html { render :new }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leases/1
  # PATCH/PUT /leases/1.json
  def update
    respond_to do |format|
      if @lease.update(lease_params)
        format.html { redirect_to @lease, notice: 'Lease was successfully updated.' }
        format.json { render :show, status: :ok, location: @lease }
      else
        format.html { render :edit }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leases/1
  # DELETE /leases/1.json
  def destroy
    @lease.destroy
    respond_to do |format|
      format.html { redirect_to leases_url, notice: 'Lease was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lease
      @lease = Lease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lease_params
      params[:lease].permit(:terms)
    end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tenant_params
      params.require(:tenant).permit(:name, :subdomain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<html>
<head>
  <title>TenantManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    <%= link_to 'Account', edit_user_registration_path %> <br>
    <%= link_to 'Log out', destroy_user_session_path, :method => :delete %><br>
<% else %>
    <%= link_to 'Sign up', new_user_registration_path %><br>
    <%= link_to 'Log in', new_user_session_path %><br>
<% end%>
<br>
<br>
<br>

<%= yield %>

</body>
</html>

app/views/leases/_form.html.erb
<%= form_for(@lease) do |f| %>
  <% if @lease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lease.errors.count, "error") %> prohibited this lease from being saved:</h2>

      <ul>
      <% @lease.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <%= f.label :terms %><br>
      <%= f.text_field :terms %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leases/edit.html.erb
<h1>Editing Lease</h1>

<%= render 'form' %>

<%= link_to 'Show', @lease %> |
<%= link_to 'Back', leases_path %>

app/views/leases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leases</h1>

<table>
  <thead>
    <tr>
      <th>Terms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leases.each do |lease| %>
      <tr>
        <td><%= lease.terms %></td>
        <td><%= link_to 'Show', lease %></td>
        <td><%= link_to 'Edit', edit_lease_path(lease) %></td>
        <td><%= link_to 'Destroy', lease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lease', new_lease_path %>

app/views/leases/new.html.erb
<h1>New Lease</h1>

<%= render 'form' %>

<%= link_to 'Back', leases_path %>

app/views/leases/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Terms:</strong>
  <%= @lease.terms %>
</p>

<%= link_to 'Edit', edit_lease_path(@lease) %> |
<%= link_to 'Back', leases_path %>

app/views/tenants/_form.html.erb
<%= form_for(@tenant) do |f| %>
  <% if @tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
      <% @tenant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing Tenant</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tenants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Subdomain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenants.each do |tenant| %>
      <tr>
        <td><%= tenant.name %></td>
        <td><%= tenant.subdomain %></td>
        <td><%= link_to 'Show', tenant %></td>
        <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
        <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New Tenant</h1>

<%= render 'form' %>

<%= link_to 'Back', tenants_path %>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tenant.name %>
</p>
<p>
  <strong>Subdomain:</strong>
  <%= @tenant.subdomain %>
</p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>